Elterninformation:
  title: Elterninformation
  text:
    - 'Liebe Eltern bzw. Erziehungsberechtigten Ihres Kindes,'
    - 'hier bei PuhHosting kann Ihr Kind sorgenfrei Produkte bestellen, wie zum Beispiel Gameserver (Auch Spielserver) um mit Freunden zusammen eine schöne Zeit in der virtuellen Welt zu verbringen.'
    - 'Sollte ihr Kind Echtgeld-Ausgaben gehabt haben, durch einen Account, der durch Falschangaben entstanden ist, ist dies kein Problem. Melden Sie sich einfach an die unten angegeben Kontaktmöglichkeiten und wir finden eine Lösung.'
    - 'Durch eine Einverständnis-Erklärung Ihrerseits, die jederzeit bei uns angefordert werden kann, ist es möglich, einen minderjährigen Account hochzustufen. Wenden Sie sich hierfür ebenfalls an die unten angegebenen Kontaktmöglichkeiten.'